version: '2'
services:
  web:
    build: .
    container_name: e-auction_web
    ports:
     - "18080:8080"
    depends_on:
     - database
    links:
     - database
    volumes:
           - ../uploads:/usr/local/tomcat/webapps/uploads/
  database:
    image: mysql:latest
    container_name: e-auction_database
    command: mysqld --user=root --verbose
    volumes:
        - ./otherfiles/e-auctions_data.sql:/docker-entrypoint-initdb.d/e-auctions_data.sql
    ports:
        - "13306:3306"
    environment:
        MYSQL_DATABASE: "test"
        MYSQL_USER: "test"
        MYSQL_PASSWORD: "test"
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

